### ISSUE TITLE
In Google Maps Adapter, layers only cleared after callbacks registered for current mode

### ISSUE THREAD

**Issue by AndrewADev** [JamesLMilner/terra-draw#100]
While working on the tests for the Google Maps Adapter, I noticed that that the `clear()` implementation will only clear layers if no callbacks have been set for the current mode (won't be called if [`_currentModeCallbacks` has not been set to a truthy value](https://github.com/JamesLMilner/terra-draw/blob/main/src/adapters/google-maps.adapter.ts#L422)).

Clicking through the demo application, I am unable to reproduce any potential errors (presumably because the callbacks are in the demo/during normal setup of TerraDraw, making the situation rather unlikely in practice). Still, it seems a bit odd to me that the layers would only be cleared if the callbacks have been set. After all, the `clearLayers()` method [already checks whether the `_layers` variable has been set](https://github.com/JamesLMilner/terra-draw/blob/main/src/adapters/google-maps.adapter.ts#L404).

So, I guess I would ask if my suspicions seem correct, and the `clearLayers()` call should happen independent of `_currentModeCallbacks`? Is that something that should be 'fixed' (moving `clearLayers` call out of `if` block)? 

I have a branch with the proposed changes (based on the test coverage changes - will be rebased if they are accepted and merged), available [here](https://github.com/AndrewADev/terra-draw/tree/fix/layers-not-cleared). If accepted, can propose the changes separately or cherry-pick them over to #98 as preferred (they bump coverage up even further, since `clearLayers()` becomes more easily testable)

**Comment by JamesLMilner** [comment]
To my understanding this should be fine as this `_currentModeCallbacks` is set when the Adapter is registered. If the adapter isn't registered then calling `clear` probably shouldn't do anything at all because the Adapter is not being used. 

The lifecycle of this is that callign 'start' on the terra draw instance will register the adapter: https://github.com/JamesLMilner/terra-draw/blob/f22074ba7828dc77bec6fbe8731a10e8e1e225ac/src/terra-draw.ts#L541

and calling 'stop' will unregister it:

https://github.com/JamesLMilner/terra-draw/blob/f22074ba7828dc77bec6fbe8731a10e8e1e225ac/src/terra-draw.ts#L633

Essentially I don't _think_ this is a problem but I'd be open to someone pointing out that this is potentially troublesome.

**Comment by JamesLMilner** [comment]
I'll leave this open a bit longer, but unless there's an identifiable issue I think this can be closed.

**Comment by JamesLMilner** [comment]
I'm going to close this for now - happy to reopen if it poses a problem.
