### ISSUE TITLE
Maplibre(Mapbox) Adapter: Source "td-point" already exists.

### ISSUE THREAD

**Issue by JinIgarashi** [JamesLMilner/terra-draw#116]
if the layer of `td-point` already exists, it shows the error of `Source "td-point" already exists` for Maplibre adapter when setMode is called.

I think we can check at the below code whether the source already exists, and only add source if it is not there
https://github.com/JamesLMilner/terra-draw/blob/868018e34d4806f13676794fbcd55870dd544d10/src/adapters/mapbox-gl.adapter.ts#L52-L61

I faced this bug because I am storing the entire style.json in the database and restoring it. So in the second time, these sources and layers are already in style, in such case, the plugin does not need to add sources again

**Comment by JamesLMilner** [comment]
Hey @JinIgarashi thanks so much for raising this - let me experiment with this and your PR and get back to you properly. I am actually in the middle of a PR for the other bug on the issue tracker to do with handling clicks which I _think_ may resolve this.

**Comment by JamesLMilner** [comment]
@JinIgarashi I'm just looking at this and trying to understand why this would be happening. The source/layer should never be added twice - it is only added one time and the cleared up when the adapter is unregistered.

Would you be able to share some of the code to reproduce the issue? Specifically am interested what you mean when you say 

>  faced this bug because I am storing the entire style.json in the database and restoring it

Look forward to resolving this for you!

**Comment by JamesLMilner** [comment]
Hey @JinIgarashi 

Thanks for getting back to me. This sounds like an exciting project, would love to see how I can help :) 

I think I see what you are doing, let me see if I can provide some guidance. I hadn't anticipated people storing the whole source/layer somewhere before but that's an interesting use case/approach. Let me suggest how I would recommend handling this :) 

I would suggest instead of storing the whole style object, instead you can use Terra Draws mechanisms to do a similar sort of thing.

For stopping you could do something like this (pseudocode):

```javascript
const snapshot = terraDraw.getSnapshot()
toLocalStorage(terraDrawDataKey, snapshot)
terraDraw.stop()
```

Then you can restore it you can do something like this:

```javascript
const snapshot = fromLocalStorage(terraDrawDataKey)
terraDraw.addFeatures(snapshot)
 ```

This keeps it in the lifecycle of Terra Draw and should achieve what you are trying to do. Here Terra Draw will handle all the styling that you have passed to the specific modes you use. I am going to add a section in [Common Patterns](https://github.com/JamesLMilner/terra-draw/blob/main/guides/COMMON_PATTERNS.md) guide to explain how to do this full flow and give an example.

Let me know if this is helpful, if not I can work with you more to make this work!

**Comment by JamesLMilner** [comment]
@JinIgarashi appreciate your persistence here! Okay, let me know how you get on - I'm happy to help you here to make sure this works as this is a very common use case. I will aim to get some good documentation around this as soon as possible.

**Comment by JamesLMilner** [comment]
Hey @JinIgarashi just wanted to check how you were getting on with this?

**Comment by JamesLMilner** [comment]
I have updated the documentation guides to cover exporting and restoring data from Terra Draw - see it here: https://github.com/JamesLMilner/terra-draw/blob/main/guides/2.STORE.md

I am going to close this issue in a little while if there's no follow up. Feel free to open a new issue if you have any further problems after that 👍🏻

**Comment by JamesLMilner** [comment]
@JinIgarashi no problem! Happy to help where I can. Don't hesitate to ask any more questions or let me know if you get stuck on anything 👍🏻
