### ISSUE TITLE
Google Maps Keyboard Interaction Issue

### ISSUE THREAD

**Issue by morehawes** [JamesLMilner/terra-draw#129]
[This](https://github.com/JamesLMilner/terra-draw/blob/79cfb5647aca092a5cf057f2bf4d559944b8afbd/src/adapters/google-maps.adapter.ts#L139-L143) seems to work for mouse events, but _keyboard_ events are being missed:

```typescript
public getMapEventElement() {
  // TODO: This is a bit hacky, maybe there is a better solution here
  const selector = 'div[style*="z-index: 3;"]';
  return this._map.getDiv().querySelector(selector) as HTMLDivElement;
}
```

This means that unlike other Adapters, feature deletion is not working for the Google Maps Adapter.

**Comment by JamesLMilner** [comment]
Hey @morehawes thanks for raising this! I think I have a feeling I know roughly what is going on here. Let me dig into it when I get a moment and see if there is a clean solution to make this work for both cursor and keyboard events for the Google Maps Adapter.

**Comment by JamesLMilner** [comment]
Okay, so I've dug into this a bit more this afternoon and it's quite strange - Google Maps seems to swallow all keyboard events, regardless of what `div` you place the event handler on. By default it also seems to set the focused element to the `body` which seems odd compared to other mapping libraries which focus on the container or an element within it.

Thank you for your PR for this, but just want to approach this slightly different by not setting this at the base.adapter level as I not sure this issue should impact other drawing adapters. The reason here is if you are not focused on the map you would not want to allow keyboard shortcuts to trigger an event like deletion etc.

Appreciate you finding this issue and your continued support here @morehawes !

**Comment by morehawes** [comment]
Hi @JamesLMilner 

Yeah it really makes things difficult!

> Thank you for your PR for this, but just want to approach this slightly different by not setting this at the base.adapter level

That makes absolute sense! I'll close that PR.

Cheers.
