### ISSUE TITLE
Calling the start() method, the event system reports an error

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#165]
![image](https://github.com/JamesLMilner/terra-draw/assets/61643801/2ab997a7-1b71-455c-9089-781673c72822)

For page opening and closing, reinitialization may cause this issue

**Comment by JamesLMilner** [comment]
Hey @Thunder7991 could you please tell me what adapter you're using and also post the sample code? It makes it much easier to help debug!

**Comment by JamesLMilner** [comment]
I feel what may of happened here is, depending on the Adapter you are using you will have to wait for the map to be ready so that Terra Draw can correctly register it's event listeners. 

For example with MapLibre, you need to wait for `style.load` event:

```typescript
map.on("style.load", () => {
	const draw = new TerraDraw({
		adapter: new TerraDrawMapLibreGLAdapter({
			map,
			coordinatePrecision: 9,
		}),
		modes: getModes(),
	});

	draw.start(); 
})
```

Check the development file for more examples of the ready events you have to wait for:

https://github.com/JamesLMilner/terra-draw/blob/main/development/src/index.ts

We should probably make this clearer in the documentation!

**Comment by JamesLMilner** [comment]
I haven't heard back here - if you are still stuck, please open a new issue with the adapter you are using and some example code that is causing you the issue. Thanks!
