### ISSUE TITLE
UX feedback

### ISSUE THREAD

**Issue by dabreegster** [JamesLMilner/terra-draw#2]
# LineString

How do you stop drawing? I've tried a few keys without effect... Escape cancels completely. `mapbox-gl-draw` uses enter to finish.

If I click while moving my mouse quickly, there's no effect -- I'm guessing there's a threshold param and it's counting as a drag. All of the sudden direction changes are a click, but only ones where I stopped long enough seem to count:

https://user-images.githubusercontent.com/1664407/202569947-7fedf407-7708-48ab-bb52-3d18152c7684.mp4

# Freehand

Feels choppy, but guessing this is known. :)

**Comment by JamesLMilner** [comment]
Hey @dabreegster - thanks so much this feedback, it's really helpful! 

Regarding LineString; yes I agree, it could be clearer on how to close it. It currently closes by clicking on the last coordinate you created, however this definitely isn't obvious and needs improving. I think a simple solution is to follow other libraries approaches of using a signifying closing coordinate that has a pointer cursor when you hover over it. I also like the idea of pressing the enter keypress to close, so may look at implementing that! 

Regarding the 'clicking whilst moving' issue - yes I can seen this occasionally with Polygon drawing as well for Leaflet. I thought I'd fixed the issue but it seems to still be rearing its head. I believe you are right with the fact that it is to do with builtin dragging behaviours. I think it can be resolved but it will take a bit of time and potentially some 'hacky' code to make it behave how one might expect. I will let you know how I get on.

Regarding Freedraw, yes it does - it is a bit of a trade off between the number of points that get created and the smoothness of the experience. More points means smoother experience but also more data. There may be some creative ways of resolving this, I'll take a look.  It is currently configurable (https://github.com/JamesLMilner/terra-draw/blob/main/src/modes/freehand/freehand.mode.ts#L30)  so as a minimum I think maybe we should increase the threshold so that it feels a bit smoother!

**Comment by dabreegster** [comment]
Thanks for the explanations!

> There may be some creative ways of resolving this

One possible alternative to rate-limiting the mouse move events is specifying a minimum distance threshold between points. This has worked reasonably well in my experience:
https://github.com/a-b-street/abstreet/blob/6b8a54d031603c3eb668105840e85b9ceed74c33/widgetry/src/tools/lasso.rs#L41

**Comment by JamesLMilner** [comment]
> Thanks for the explanations!
> 
> > There may be some creative ways of resolving this
> 
> One possible alternative to rate-limiting the mouse move events is specifying a minimum distance threshold between points. This has worked reasonably well in my experience:
> https://github.com/a-b-street/abstreet/blob/6b8a54d031603c3eb668105840e85b9ceed74c33/widgetry/src/tools/lasso.rs#L41

Of course, no problem :)

With regards to minimum distance threshold, that's a great idea! I will definitely experiment with that when I get a chance.

**Comment by dabreegster** [comment]
Thanks for splitting out more specific issues, this one can be closed now
