### ISSUE TITLE
[Potential Bug] The circle is scaled repeatedly, causing irregular shape problems.

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#247]
> ## Description of Changes
> It was not taking into account that the center was the geodesic center and not the web mercator center. This caused movement of the polygon as it was resized.
> 
> ## Link to Issue
> Potentially resolves #243 but hard to say without more feedback.
> 
> ## PR Checklist
> * [x]  There is a associated GitHub issue
> * [x]  If I have added significant code changes, there are relevant tests
> * [ ]  If there are behaviour changes these are documented

Hey， @JamesLMilner . Now the scaling effect experience for the circle has been improved, but if the circle is scaled to a very small time to zoom again, repeated operations, there will be circular irregularities. Repeated testing will cause this problem.

_Originally posted by @Thunder7991 in https://github.com/JamesLMilner/terra-draw/issues/244#issuecomment-2095124409_

**Comment by JamesLMilner** [comment]
There is a possibility these irregularities were caused by the fact that until the last release the initial circles were created as a geodesic circle. This introduces 'irregularities' if you are expecting a prefect circle in the web mercator projection. The default behaviour in the newest release is to draw the circle as web mercator (this can be adjusted by using `projection: "globe"` if you want to go back to drawing a geodesic circle by default. 

Please feel free to raise a new issue if this behaviour change has not resolved the irregularities.
