### ISSUE TITLE
Excalidraw library integration

### ISSUE THREAD

**Issue by buildvoc10** [JamesLMilner/terra-draw#25]
Hello watched your FOSS4G talk, thanks for sharing this project.
Currently working on a project using mapbox and ordinance survey data for collection geotagged photos in the field. (see protype https://buildingshistory.co.uk/#18.25/51.367998/-2.202375/0/37
Currently you can import/export geojson features buildings, was wondering if you have considered integrating terra-draw with Excalidraw library? https://github.com/excalidraw/excalidraw 
My use case would be able to add/edit polygons in browser but have version control via excalidraw.

**Comment by JamesLMilner** [comment]
Hey @buildvoc10  - thank you for showing your interest in Terra Draw. I'm glad you found the FOSS4G talk interesting!

As for your suggestion on integrating Terra Draw with the Excalidraw library, I must admit that I haven't considered this integration before, mostly due to perceived complexity of that sort of integration. However, it seems like an interesting idea and I appreciate you bringing it to my attention.

Regarding version control, it has indeed been on my mind, and I have considered adding this feature to Terra Draw or at least showing how to make it happen via a guide or example project . While I cannot provide a specific timeline at the moment, it is something that I may potentially work on soon.

I encourage you to keep an eye on the project's GitHub page for updates, and please don't hesitate to share any additional ideas or suggestions you might have. Your feedback is greatly appreciated!

**Comment by buildvoc10** [comment]
@JamesLMilner have been using excalidraw for about 2 years, a nice function is being able have files offline and save a version of the sketch ( date automatically completed)
-grid is helpful 
-grouping 
-libraries (for templates)
-export to json 

Excalidraw is a complex app, but the functionality and interoperability are second to none.If you would like to do some testing having is running on a server you can use.
