### ISSUE TITLE
Base Adapter "getDrawEventFromEvent" BUGS

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#26]
First of all thanks for sharing the project. ❤️ 

### Current State:
If the parent element of the mapContainer has an offset, the cursor position is not calculated correctly.

### Problem:
Currently the map container is being goten.
https://github.com/JamesLMilner/terra-draw/blob/8f4e6f35771cd82d89823c66878a4e64732397b0/src/adapters/common/base.adapter.ts#L297
Then its offsetLeft and offsetTop properties are used to calculate containerX and containerY.
https://github.com/JamesLMilner/terra-draw/blob/8f4e6f35771cd82d89823c66878a4e64732397b0/src/adapters/common/base.adapter.ts#L301
This properties get the offset from the parent only, but dont take into account the total offset if the map container is highly nested in the DOM.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetLeft

### Proposal:
Use the same approach of the mapbox-gl adapter on its method getLngLatFromEvent
https://github.com/JamesLMilner/terra-draw/blob/8f4e6f35771cd82d89823c66878a4e64732397b0/src/adapters/mapbox-gl.adapter.ts#L174

Other approach could be to use the "project" method since latlng is already calculated at that point.

### Current State:
You cant use the rotate and scale functionality, not even in the official demo: https://terradraw.io/ 
I tested it on Chrome and Edge

### Problem:
Spreading the Set, it seems to be a problem with Typescript.
https://github.com/JamesLMilner/terra-draw/blob/8f4e6f35771cd82d89823c66878a4e64732397b0/src/adapters/common/base.adapter.ts#L304

### Proposal:
Convert the set to array and then spread it.

**Comment by JamesLMilner** [comment]
Hey @alanOracle thanks for raising these. I'm really glad you like the project and I appreciate you taking the time to write up this error report. 

I have some good news, which is this that both of these should now be fixed in `0.0.1-alpha.27` which is available via GitHub. You check the rotation now works on [https://terradraw.io](https://terradraw.io)

Please feel free to raise any other issues you may find on your travels, I want to make Terra Draw a great experience for everyone to use and squashing bugs is a big part of that!
