### ISSUE TITLE
How to disable the right -click event?

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#284]
In Mapbox, the prohibition of rotating operations failed, and after investigation, it was caused by the right-click time conflict with Terra-Draw.

**Comment by JamesLMilner** [comment]
Right click would only disabled rotations if the user is in select mode and their cursor over a coordinate - this happens so we can intercept the event to be able to move or delete coordinates, or reposition a geometry in Terra Draw. I wasn't able to make this occur outside of that expected behaviour:

https://github.com/user-attachments/assets/68a4a26d-c476-4c4a-a1e8-6243b44e1789

If you have specific detailed reproduction steps please share them.

**Comment by JamesLMilner** [comment]
Without further detailed information on the issue here I'll have to close this out unfortunately. Feel free to open a new issue if you have detailed instructions on how to reproduce. Perhaps a video would help clarify.
