### ISSUE TITLE
Add way to programmatically add features to drawing instance

### ISSUE THREAD

**Issue by JamesLMilner** [JamesLMilner/terra-draw#32]
Having a top level API to add features to a Terra Draw instance would be valuable and has been raised by @bdon separately. Other drawing libraries have this feature. There is already a `data` property that can be used to load data at instantiation but actually I believe this would be better superseded by a `addFeatures` method at on the Terra Draw instance and the data property becomes deprecated. The complex part would be validating features, but I think we can do this by adding a method called `validateFeature` to all modes that ensures the mode geometry is valid.

**Comment by bdon** [comment]
The use case here is uploading / pasting a GeoJSON and then letting the loaded geometry have editable vertices. A good starting point would be making it work for the Rectangle mode because all geometries are simple and valid as long as they're nonzero and do not lie outside valid extents (should handle antemeridian wrapping however)

**Comment by JamesLMilner** [comment]
This is now possible in the `0.0.1-alpha.32` release. I've written some basic guides on how to get it working:

https://github.com/JamesLMilner/terra-draw/blob/main/guides/GETTING_STARTED.md#common-patterns
