### ISSUE TITLE
Preventing Polygon Self-Intersection with Select Mode

### ISSUE THREAD

**Issue by UncatchableAlex** [JamesLMilner/terra-draw#64]
Although there is a flag in the constructor for TerraDrawPolygonMode objects to prohibit self-intersections, polygons subsequently drawn in polygon mode can be modified in select mode to become self-intersecting. Ideally, there would be some way to specify in the constructor for TerraDrawSelectMode whether or not to prohibit self-intersections of polygons. Here is an example of what a call to the TerraDrawSelectMode constructor could look like:

```typescript
new TerraDrawSelectMode({
      flags: {
        polygon: {
          feature: {
            draggable: false,
            rotateable: false,
            scaleable: false,
            self-intersectable: false,
            coordinates: {
              midpoints: true,
              draggable: true,
              deletable: true,
            },
          },
        }
      }
    })
```

 I intend to submit a pull request to add this feature. I'm not yet sure what changes I will make under the hood because I haven't started tinkering yet. Any advice is welcome :)

**Comment by JamesLMilner** [comment]
This is a _great_ idea. 

I think this could be achieved by editing the onDrag event for select mode to do something to what we do with onClick in polygon mode here:

https://github.com/JamesLMilner/terra-draw/blob/main/src/modes/polygon/polygon.mode.ts#L387

You may need to update `DragCoordinateBehavior`  to do a check using the `selfIntersect` function, probably changing the API schema for `drag` to something like this:

```typescript
	public drag(event: TerraDrawMouseEvent, allowSelfIntersection: boolean): boolean {
```

Then checking the update geometry returns false before we do the update (otherwise just early returning like we do for coordinates that are out of bounds). You'l have to wrap the updated geometry  in a Feature as the selfIntersects takes a Feature<Polygon> type. It would probably end up something like this:

```typescript
if (geometry.type !== 'Point' && !allowSelfIntersection && selfIntersects({ type: "Feature", geometry, properties: {}})) {
			return false;
}
```

**Comment by JamesLMilner** [comment]
Closed by accident as I tagged the wrong issue in https://github.com/JamesLMilner/terra-draw/pull/69 🤦🏻

**Comment by JamesLMilner** [comment]
This is now resolved thanks to @UncatchableAlex - great work! 🎉
