### ISSUE TITLE
Unit test Google Maps Adapter

### ISSUE THREAD

**Issue by JamesLMilner** [JamesLMilner/terra-draw#88]
Adapters are the way in which we allow Terra Draw to work across different mapping libraries. An Adapter provides the code to map the library specific code to our more generalised Terra Draw interfaces so that all the Adapters can behave in the same way.

The unit test coverage for the Google Maps Adapter isn't where it should be, ideally we'd want to go for 80% +. It would be great to bring this up to speed! We have some guidance for new contributors [here](https://github.com/JamesLMilner/terra-draw/blob/main/guides/CONTRIBUTING.md) and also a guide on how to develop locally [here](https://github.com/JamesLMilner/terra-draw/blob/main/guides/DEVELOPMENT.md)

If you need inspiration on how to do this, you can see some example tested unit tests here:

ArcGIS Maps SDK Adapter:
https://github.com/JamesLMilner/terra-draw/blob/main/src/adapters/arcgis-maps-sdk.adapter.spec.ts

Leaflet.js Adapter:
https://github.com/JamesLMilner/terra-draw/blob/main/src/adapters/leaflet.adapter.ts

**Comment by AndrewADev** [comment]
Hey @JamesLMilner, 

I've started working on some changes for this, and ran into a slight 'snag', or at least something probably worth discussing first: currently the Google Maps adapter has some [direct references to DOM globals like `document`](https://github.com/JamesLMilner/terra-draw/blob/main/src/adapters/google-maps.adapter.ts#L165), and the [Jest environment is set to `node`](https://github.com/JamesLMilner/terra-draw/blob/main/jest.config.ts#L14), as opposed to, say, `JSDOM`.

I poked around rather briefly, and it looks like one of the [only other direct references](https://github.com/JamesLMilner/terra-draw/blob/main/src/adapters/leaflet.adapter.ts#L37) to `document` (in an adapter) is not currently covered by the tests:
![image](https://github.com/JamesLMilner/terra-draw/assets/2937540/192468f5-62c5-49e5-a85e-4b8fc4e214c1)


Is the use of `node` environment for tests intentional? (Would need refactoring to avoid direct references to globals like this) Or is it already planned to use something like `JSDOM` for these situations?



Otherwise, I have my branch with early changes available [here](https://github.com/AndrewADev/terra-draw/tree/test/improve-google-maps-coverage). Feel free to take a look, and let me know, if that's about what you were expecting (:warning: WIP and subject to rebasing!)

**Comment by JamesLMilner** [comment]
Hey @AndrewADev thanks for your interest and detailed message - really nice to hear from you.

It's a great question - I guess using JSDOM would probably make more sense here. I wonder if it's just a case of changing the jest config? The other alternative if it's just a couple of places would be to just do a mock with jest directly (something like `jest.spyOn(document, 'createElement') might work. I'm open to whatever helps you get it working or is simplest. I would be interested to know if changing to JSDOM has an impact on performance being the only thing?

To answer your question about the branch - looking at your code this is exactly the kind of thing I had in mind!

**Comment by AndrewADev** [comment]
@JamesLMilner thanks your response and sorry for the delayed answer - I wanted to try some things out before responding and it took me longer than expected to get the test coverage up to where it needed to be.

I've gone with JSDOM, since that is definitely the simplest option here. Prior to posting the question I tried a few things to mock some of the DOM methods, but none of them worked (can't recall if I tried the method you suggest or not).

> I wonder if it's just a case of changing the jest config?

For Jest, there is another package that needs added (`jest-environment-jsdom`). After that it can be as simple as setting the environment, yes. Note though, that setting the environment in the jest config would set it like that for _all specs_. It is also possible to set the environment [_per spec_](https://jestjs.io/docs/configuration#testenvironmentoptions-object), which I've done in the PR (I've used this a number of times before, as it can be very useful if the main environment either doesn't provide proper emulation of a certain method, or perhaps clashes with a global method, or there are performance concerns, etc).

I didn't do any proper performance testing (though did at least try out [Happy DOM](https://github.com/capricorn86/happy-dom)), but the spec with JSDOM environment felt similar, possibly even faster at times. In any case, only changing the environment for a single spec file should minimize any possible performance issues.

As to the PR - the changes themselves are ready. At this point I'm just trying to figure out how to get the project running and click around through a live instance to ensure I didn't break anything (was mostly working in a test loop). I will move it to "ready" as soon as I can confirm that (or let me know if you have confirmed).
